# netlify.toml for TMA deployment

[build]
  # Build command for TMA
  command = "npm install && npm run build"
  # Published directory - where static files are served from
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"

# Basic redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200