# netlify.toml for web deployment

# [functions] - Функции отключены для web-сайта
# Все функции находятся ТОЛЬКО в bot-сайте: sparkling-cupcake-940504.netlify.app
# Web-сайт содержит только статичные файлы

# Build settings for web version
[build]
  # Build command for web version
  command = "npm install && npm run build"
  # Published directory - dist folder in web directory
  publish = "dist"

# Environment variables needed for build
[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"

# API proxy: проксируем все вызовы на bot-сайт, чтобы куки были first-party для Safari
[[redirects]]
  from = "/api/*"
  to = "https://sparkling-cupcake-940504.netlify.app/.netlify/functions/:splat"
  status = 200
  force = true

# SPA fallback - все неизвестные роуты перенаправляем на index.html для Vue роутера
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200